crossplane-contrib/provider-gitlab

- apis/projects/v1alpha1/project_types.go
- package/crds/projects.gitlab.crossplane.io_projects.yaml
- pkg/controller/projects/project.go
- pkg/controller/projects/project_test.go
- use project id instead of path/name combination as `external-name`, which makes creating a project referencer easier (e.g. for project hooks)
- drop tests for updating external-name
Note that this is a breaking change but given that we don't have a release yet I think we can get away with it
Fixes #7 
I have:
manually created a `project` without setting an `annotation` and deleting it again.
> use project id as external-name

- README.md
- apis/v1beta1/providerconfig_types.go
- examples/providerconfig/provider.yaml
- go.mod
- go.sum
- package/crds/gitlab.crossplane.io_providerconfigs.yaml
- pkg/clients/gitlab.go
- move baseURL to ProviderConfig and document in readme
it's now easier to target a different gitlab instance:
```yaml
apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
name: gitlab-provider
spec:
baseURL: https://gitlab.com/
credentials: [...]
```
Fixes #8 
I have:
manual
> move baseURL to top-level ProviderConfig

- Makefile
- apis/groups/v1alpha1/group_types.go
- apis/groups/v1alpha1/zz_generated.deepcopy.go
- apis/projects/v1alpha1/project_types.go
- apis/projects/v1alpha1/zz_generated.deepcopy.go
- cluster/local/integration_tests.sh
- examples/groups/group.yaml
- examples/projects/project.yaml
- package/crds/groups.gitlab.crossplane.io_groups.yaml
- package/crds/projects.gitlab.crossplane.io_projects.yaml
- pkg/clients/groups/group.go
- pkg/clients/projects/project.go
- pkg/clients/projects/project_test.go
Adds a new `name` field to `Group` and `Project` resources - this allows users to set a 'human readable' name for their `Group` or `Project` that is free of the restrictions placed on the `metadata.name` of a resource.
Closes #41
I have:
An additional test has been added to each resource to validate the override behaviour of the `name` field.
> Add name field to group and project

- pkg/controller/groups/group.go
- pkg/controller/groups/group_test.go
- pkg/controller/projects/project.go
- pkg/controller/projects/project_test.go
Forgot to implement up to date checking of the new `name` fields added in #42.
This adds additional checks to the `upToDate` methods, and adds a test for it on the `Project` resource.
I can't for the life of me work out how to add a suitable test within the existing framework for the `Group` resource - regardless of what I set, the test always passes when it should fail without the fixes to the `upToDate` method. Any ideas @janwillies ?
I have:
Additional test added for Project. Group change is untested but identical.
> Make sure project and group name is checked for updates

- apis/groups/v1alpha1/group_types.go
- apis/projects/v1alpha1/project_types.go
- package/crds/groups.gitlab.crossplane.io_groups.yaml
- package/crds/projects.gitlab.crossplane.io_projects.yaml
- pkg/clients/groups/group.go
- pkg/clients/projects/project.go
- pkg/controller/groups/group_test.go
- pkg/controller/projects/project_test.go
Signed-off-by: Benedikt Bock <benedikt.bock-extern@deutschebahn.com>
(external expert on behalf of DB Netz AG)
Fixes #54: Removed plain text `runnersToken` from the observation objects of group and project MR
I have:
Tests and examples
> remove plaintext runner token from observation

- pkg/clients/projects/variable.go
- pkg/clients/projects/variable_test.go
- pkg/controller/projects/variables/controller.go
When creating, updating or deleting variables, variables with identical key names were overwritten despite having distinct environment scopes.
* Added function that will generate a variable filter struct and added it where needed.
* Added functions that generate variable options for get and remove operations.
Fixes #70
I have:
* Tested in my local cluster. Creating, updating and deleting doesn't affect other variables.
* Ran `make e2e`.
> fix: project var overwites despite distinct env scope

- cluster/local/integration_tests.sh
Changed the condition for the while loop that waits for the number of `providerrevision.pkg.crossplane.io` to reach 0 to complete the test.
Changed the expression in the condition of the while loop that waits for the deletion of the provider to complete.
Instead of waiting for the result to be a literal string with the value `"0"`, it will first convert it to an integer. The conversion to an integer will strip away any white spaces. On MacOS X, the command returns the correct value but it has leading white spaces which causes the loop to become infinite. Converting it to an integer first gets around this issue.
Fixes #71 
I have:
I've run `make e2e`.
> fix(e2e): change while loop that waits for deletion

- pkg/clients/groups/group.go
- pkg/clients/groups/group_test.go
Fixes #77
Add nil check for ExpiresAt in GenerateObservation func
unit test: "SharedWithGroupExpiresAtIsNil"
> fix(group): add nil check for ExpiresAt in GenerateObservation func

- pkg/controller/projects/project.go
- pkg/controller/projects/project_test.go
Fixes #74 
For already created resources it will require to remove "MirrorUserID" value from managed resource.
Unit Test
> fix(projects): Avoid setting MirrorUserID in lateInitialize() if atProvider value is 0 (default value)

- pkg/clients/groups/deploytoken.go
- pkg/clients/groups/fake/fake.go
- pkg/clients/projects/fake/fake.go
- pkg/controller/groups/deploytokens/controller.go
- pkg/controller/groups/deploytokens/controller_test.go
- pkg/controller/groups/group.go
- pkg/controller/groups/group_test.go
- pkg/controller/groups/members/controller.go
- pkg/controller/groups/members/controller_test.go
- pkg/controller/projects/accesstokens/controller.go
- pkg/controller/projects/accesstokens/controller_test.go
- pkg/controller/projects/deploykeys/controller.go
- pkg/controller/projects/deploykeys/controller_test.go
- pkg/controller/projects/deploytokens/controller.go
- pkg/controller/projects/deploytokens/controller_test.go
- pkg/controller/projects/hooks/controller.go
- pkg/controller/projects/hooks/controller_test.go
- pkg/controller/projects/members/controller.go
- pkg/controller/projects/members/controller_test.go
- pkg/controller/projects/project.go
- pkg/controller/projects/project_test.go
- pkg/controller/projects/variables/controller.go
- pkg/controller/projects/variables/controller_test.go
Fixes #85 
groups.deploytoken.Observe: 
- switch from `ListGroupDeployTokens` to `GetGroupDeployToken`
- add `GroupID` nil check
- add `err` nil check
- add `response status` 404 check on `get`
groups.group.Observe:
- add `response status` 404 check on `get`
groups.member.Observe:
- add `response status` 404 check on `get`
projects.accesstoken.Observe:
- add `response status` 404 check on `get`
projects.deploykey.Observe:
- add `response status` 404 check on `get`
- remove returned resource nil check
projects.deploytoken.Observe:
- add `response status` 404 check on `get`
- remove returned resource nil check
projects.hook.Observe:
- add `response status` 404 check on `get`
projects.member.Observe:
- add `response status` 404 check on `get`
- remove returned resource nil check …
> fix: Add 404 response status ignore in Observe

- apis/groups/v1alpha1/referencers.go
add nil check for `ParentID` in ResolveReferences() for group. 
I have:
> fix(group): add nil check before ParentID dereferencing in ResolveReferences()

- pkg/controller/projects/deploytokens/controller.go
- Add nil check before pointer deref for ProjectID in controller
I have:
> fix(projects.deploytoken): Add nil check before pointer deref for ProjectID in controller

- pkg/controller/groups/group.go
- Add nil check before pointer deref for GroupID in controller
- Adjust code, dependent on the changes
I have:
> fix(groups.group): Add nil check before pointer deref for GroupID in controller

- pkg/controller/groups/deploytokens/controller.go
Add nil check before pointer deref for GroupID in controller
I have:
> fix(groups.deploytoken): Add nil check before pointer deref for GroupID in controller

- pkg/clients/gitlab.go
- pkg/controller/projects/deploykeys/controller.go
- Add nil check before pointer deref for CreatedAt in controller
I have:
> fix(projects.deploykey): Add nil check before pointer deref for CreatedAt in controller

- apis/groups/v1alpha1/referencers.go
Fixes https://github.com/crossplane-contrib/provider-gitlab/issues/117
I have:
> fix(group): Ignore empty resolve values in referencers

- pkg/clients/gitlab.go
Fixes a panic due to a nil deref when using a config with `InsecureSkipVerify: true`.
I have:
> fix: Nil panic for InsecureSkipVerify

- apis/groups/v1alpha1/group_types.go
- package/crds/groups.gitlab.crossplane.io_groups.yaml
`SharedWithGroupsObservation` childs are no longer required.
I have:
na
> fix(groups): SharedWithGroupsObservation fields no longer required

- cmd/provider/main.go
Add a default no-op logger so that the controller-runtime isn't producing a stack trace.
Other providers are already using the same solution to avoid this problem:
- provider-kubernetes: https://github.com/crossplane-contrib/provider-kubernetes/blob/main/cmd/provider/main.go#L74-L75
- provider-helm: https://github.com/crossplane-contrib/provider-helm/blob/master/cmd/provider/main.go#L64-L65
Fixes #150 
I have:
Manually built & run test suite.
> fix missing logger

- README.md
- apis/v1beta1/providerconfig_types.go
- examples/providerconfig/provider.yaml
- package/crds/gitlab.crossplane.io_providerconfigs.yaml
- pkg/clients/gitlab.go
Adding support of different authentification types supported by the gitlab SDK:
[BasicAuth](https://docs.gitlab.com/ee/user/application_security/dast/browser/checks/287.1.html) with username and password, [JobToken](https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html), [OAuthToken](https://docs.gitlab.com/ee/api/oauth2.html), [PersonalAccessToken](https://docs.gitlab.com/ee/security/tokens/#personal-access-tokens) that stays the default for retro-compatiability in mind.
I have:
This version is running in production.
> feat(authentication): add support for all authentification types

- cmd/provider/main.go
- pkg/controller/groups/accesstokens/controller.go
- pkg/controller/groups/deploytokens/controller.go
- pkg/controller/groups/groups/group.go
- pkg/controller/groups/members/controller.go
- pkg/controller/groups/samlgrouplinks/controller.go
- pkg/controller/groups/variables/controller.go
- pkg/controller/projects/accesstokens/controller.go
- pkg/controller/projects/deploykeys/controller.go
- pkg/controller/projects/deploytokens/controller.go
- pkg/controller/projects/hooks/controller.go
- pkg/controller/projects/members/controller.go
- pkg/controller/projects/pipelineschedules/controller.go
- pkg/controller/projects/projects/project.go
- pkg/controller/projects/variables/controller.go
- pkg/features/features.go
This PR promotes the ManagementPolicies from an alpha feature to a beta feature.
This aligns with the promotion crossplane did while moving to 1.17+.
Fixes #169
I have:
Unit tests and deployed internally.
> Promote ManagementPolicies to beta

- pkg/clients/groups/samlgrouplink.go
- pkg/controller/groups/samlgrouplinks/controller_test.go
Add missing MemberID to the SAMLGroupLink object. This allows the mapping of custom Gitlab Roles to a SAML Group.
Fixes #157
I have:
Unit testing
> Fix SAMLGroupLink MemberID mapping

- apis/gitlab.go
Fixes ExternalSecretStores feature prevention to crash the application 
Fixes https://github.com/crossplane-contrib/provider-gitlab/issues/175
I have:
Running compiled binary locally with flag enabled
Detail for fix
Registering missing scheme: 
```
func init() {
// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
AddToSchemes = append(AddToSchemes,
gitlabv1beta1.SchemeBuilder.AddToScheme,
groupsv1alpha1.SchemeBuilder.AddToScheme,
projectsv1alpha1.SchemeBuilder.AddToScheme,
gitlabv1alpha1.SchemeBuilder.AddToScheme, // HERE
)
}
```
> fix ExternalSecretStores feature fail to start, fixes #175

- pkg/clients/gitlab.go
This issue fixes the mapping between the different supported Credential Method (BasicAuth, JobToken, OAuthToken or PersonalAccessToken) defined in the ProviderConfig.
I have:
I have run this on my cluster and have got a positive status on a `Hook.projects.gitlab.crossplane.io` ressource
> fix(client): map AuthMethod for different supported token types

- pkg/clients/gitlab.go
The Basic Auth client does not get the same options passed to it as the other clients. This is inconvenient because it removes the ability to use the `InsecureSkipVerify` option.
This PR configures the Basic Auth client like all the others.
I have:
Ran `build run` and verified that the Basic Auth client works with the `InsecureSkipVerify` option.
Used this PR's version of the provider to create a project and group within Gitlab with no issues using the Basic Auth client.
> fix: pass options to basic auth client

- go.mod
- go.sum
- pkg/clients/groups/fake/fake.go
- pkg/clients/groups/group_test.go
- pkg/clients/groups/variable.go
- pkg/controller/groups/accesstokens/controller_test.go
- pkg/controller/groups/groups/group_test.go
- pkg/controller/groups/variables/controller.go
- pkg/controller/projects/accesstokens/controller_test.go
* update of the Gitlab client-go dependency to [v0.127.0](https://gitlab.com/gitlab-org/api/client-go/-/releases/v0.127.0)
I have:
> chore: update gitlab client-go to version v0.127.0

- pkg/controller/projects/deploykeys/controller.go
* Dereferenced ProjectID in the UpdateDeployKey call.
Fixes #198
I have:
> fix: dereference projectId for UpdateDeployKey call

- apis/groups/v1alpha1/group_types.go
- apis/groups/v1alpha1/zz_generated.deepcopy.go
- package/crds/groups.gitlab.crossplane.io_groups.yaml
- pkg/controller/groups/groups/group.go
- pkg/controller/groups/groups/group_test.go
Adds a new property to specify if the controller should treat groups in pending deletion state as deleted.
Relates to https://github.com/crossplane-contrib/provider-gitlab/pull/212 and #207.
I have:
Manually
> feat(group): Add option to treat pending deletion as deleted
